/assistant:
    post:
        description: Send a message to Google Assistant API
        tags:
            - Assistant
        produces:
            - application/json
        requestBody:
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/assist"
        responses:
            "200":
                $ref: "#/components/responses/assist"
            "400":
                $ref: "#/components/responses/BadRequest"
            "401":
                $ref: "#/components/responses/Unauthorized"
            "403":
                $ref: "#/components/responses/Forbidden"
            "409":
                $ref: "#/components/responses/Conflict"
            "500":
                $ref: "#/components/responses/InternalServerError"
